version: '3'

services:
  mysql:
    image: mysql
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
     - ./.database:/var/lib/mysql